In [7]:
import torch

In [14]:
a = torch.column_stack((torch.ones(4,1), torch.rand((4,4))))

In [15]:
a

tensor([[1.0000, 0.2185, 0.0644, 0.1475, 0.8535],
        [1.0000, 0.5371, 0.1471, 0.7940, 0.8874],
        [1.0000, 0.4707, 0.9594, 0.5345, 0.0336],
        [1.0000, 0.2936, 0.1258, 0.0572, 0.1923]])

In [17]:
torch.nn.functional.dropout(a, p=0)

tensor([[1.0000, 0.2185, 0.0644, 0.1475, 0.8535],
        [1.0000, 0.5371, 0.1471, 0.7940, 0.8874],
        [1.0000, 0.4707, 0.9594, 0.5345, 0.0336],
        [1.0000, 0.2936, 0.1258, 0.0572, 0.1923]])

In [1]:
import pandas as pd

In [16]:
df = pd.read_csv('MG17.csv', header=None)

In [21]:
df.shape

(1, 10000)

In [25]:
torch.tensor(pd.read_csv('MG17.csv', header=None).T.to_numpy())

tensor([[ 0.0322],
        [ 0.0404],
        [ 0.0579],
        ...,
        [-0.1956],
        [-0.1368],
        [-0.0822]], dtype=torch.float64)

In [ ]:
from DATA import MG17